### ISSUE TITLE
A small question with the fast downward part

### ISSUE THREAD

**Issue by Bowen-He** [ronuchit/pddlgym_planners#9]
Hi thanks so much for developing the code library! 
I'm trying to use the library along with PDDLgym for some research experiments. I got a small issue with the planner when I run experiments. It looks like the planner creates some temporary sas_plan file when plans for PDDLGym environments, and when I run for multiple seeds in parallel, the name conflict may raise an error in the code. I'm wondering where I may change the temporary file name in the code so that it could prevent this issue from happening. 
Thanks a lot!

**Comment by ronuchit** [comment]
Hey! Those file names come from inside the fast_downward planner itself. Here are the arguments I'd recommend overriding if you're planning to run the planner in parallel:
https://github.com/aibasel/downward/blob/main/driver/arguments.py#L417-L424
(Specifically, `--plan-file` and `--sas-file`.)

Looking at the command string we generate in our repo in `fd.py`:
https://github.com/ronuchit/pddlgym_planners/blob/master/pddlgym_planners/fd.py#L37
I see that `--sas-file` is already handled by passing in `sas_file` which was set to `tempfile.NamedTemporaryFile(delete=False).name`. Hence, you should be able to fix your issue by doing something similar for `--plan-file` as well. You should be able to use the `final_flags` init argument to achieve this:

```
plan_file = tempfile.NamedTemporaryFile(delete=False).name
fd_planner = FD(..., final_flags=f"--plan-file {plan_file}")
```

Try it out and let us know here if it works!

**Comment by Bowen-He** [comment]
Great thanks! I think that's exactly what I was looking for!
